/* micron/version.h
   Generated by Micron build process on:
   Mon Aug  5 01:38:30 PM CEST 2024 */

#ifndef MICRON_VERSION_H
#define MICRON_VERSION_H 1

#define MICRON_VER_MAJ 0
#define MICRON_VER_MIN 1

#define MICRON_STRVER "0.1"

/* The version number is created by combining the major and minor number,
   with the major number offset by 16 bits to the left. */
#define MICRON_VER 0x00000001

#endif /* MICRON_VERSION_H */
